# Build Docker Jinja Container
FROM {{ dockerUser + "/" + buildImageName + ":" + buildImageVersion }}
LABEL maintainer="{{ dockerUser }} <{{ dockerUserEmail }}>"
USER root

# Install Docker Jinja
# hadolint ignore=DL3013,DL3018
RUN pip3 install --upgrade --no-cache-dir j2cli[yaml] && \
    mkdir /project && \
    chown "${ALPINE_USER}":"${ALPINE_USER}" /project

VOLUME ["/project"]
WORKDIR /project
USER ${ALPINE_USER}
CMD ["j2"]

